server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:8100"
              - "http://localhost:8101"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: service-utilisateurs
          uri: lb://service-utilisateurs
          predicates:
            - Path=/api/auth/**, /api/users/**

        # ── NOUVEAU ──────────────────────────────────────
        - id: service-abonnements
          uri: lb://service-abonnements
          predicates:
            - Path=/api/abonnements/**

        - id: service-offres
          uri: lb://service-offres
          predicates:
            - Path=/api/offres/**

        - id: service-suivi
          uri: lb://service-suivi
          predicates:
            - Path=/api/suivi/**

        - id: service-optimisation
          uri: lb://service-optimisation
          predicates:
            - Path=/api/itineraires/**

        - id: service-alertes
          uri: lb://service-alertes
          predicates:
            - Path=/api/alertes/**

        - id: service-messagerie
          uri: lb://service-messagerie
          predicates:
            - Path=/api/messages/**, /ws/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

jwt:
  secret: "agriconnect@2026#cameroun!XyZ789"